#!/bin/bash
#SBATCH -J ugi_chemprop
#SBATCH -A LEE-WJM41-SL2-GPU
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --time=1:00:00
#SBATCH --mail-user=wjm41@cam.ac.uk
#SBATCH --mail-type=ALL
#SBATCH -p pascal

. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-gpu
module load intel/bundles/complib/2019.3
module unload cuda/8.0
module load cuda/10.1

module load miniconda/3
source activate chemprop

DIR=/rds-d2/user/wjm41/hpc-work/datasets/Ugis
model_dir=/rds-d2/user/wjm41/hpc-work/models

chemprop_train --data_path $DIR/ugis_processed.csv \
               --separate_test_path $DIR/docked2/ugis_processed.csv \
               --dataset_type regression \
               --save_dir ugi_chemprop \
               --features_generator rdkit_2d_normalized --no_features_scaling

