#!/bin/bash
#SBATCH -J ugi_multi_test
#SBATCH -A LEE-WJM41-SL2-GPU
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:4
#SBATCH --time=0:30:00
#SBATCH --mail-user=wjm41@cam.ac.uk
#SBATCH --mail-type=ALL
#SBATCH -p pascal

. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-gpu
module load intel/bundles/complib/2019.3
module unload cuda/8.0
module load cuda/10.1

module load miniconda/3
source activate dgl_life

DIR=/rds-d2/user/wjm41/hpc-work/datasets/Ugis
model_dir=/rds-d2/user/wjm41/hpc-work/models
save_name=multi_demo2

python $DIR/scripts/mpnn_batched_multi.py -p $DIR/datasets/ugis_processed.csv \
                             -batch_size 512 \
                             -n_epochs 150 \
                             -lr 1e-2 \
                             -save_name $save_name \
                             -val_path $DIR/docked2/ugis_processed.csv \
                             -write_batch 10 \
                             --gpus 0,1,2,3
                             #-load_name $model_dir/model_epoch_1.pt
