#!/bin/bash
#SBATCH -J ugi_val_gat
#SBATCH -A LEE-WJM41-SL2-GPU
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --time=8:00:00
#SBATCH --mail-user=wjm41@cam.ac.uk
#SBATCH --mail-type=ALL
#SBATCH -p pascal

. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-gpu
module load intel/bundles/complib/2019.3
module unload cuda/8.0
module load cuda/10.1

module load miniconda/3
source activate dgl_life

DIR=/rds-d2/user/wjm41/hpc-work/datasets/Ugis
model_dir=/rds-d2/user/wjm41/hpc-work/models

python gat_batched.py -p $DIR/docked2/ugis_processed.csv -n_trials 1 -batch_size 1024 -n_epochs 150 -ts 0 -lr 1e-2 -save_name val_gat -val_path $DIR/docked2/ugis_processed.csv -write_batch 10 #-load_name $model_dir/model_epoch_1.pt
