name: Tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: setup.py

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dock2hit
          environment-file: environment_cpu.yml
          python-version: 3.9

      - name: Install dock2hit + dependencies
        shell: bash -l {0}
        run: |
          pip install .

      - name: Run tests
        shell: bash -l {0}
        run: pytest test/ --cov dock2hit
